require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CategorisController do

  def mock_categori(stubs={})
    @mock_categori ||= mock_model(Categori, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all categoris as @categoris" do
      Categori.stub(:all) { [mock_categori] }
      get :index
      assigns(:categoris).should eq([mock_categori])
    end
  end

  describe "GET show" do
    it "assigns the requested categori as @categori" do
      Categori.stub(:find).with("37") { mock_categori }
      get :show, :id => "37"
      assigns(:categori).should be(mock_categori)
    end
  end

  describe "GET new" do
    it "assigns a new categori as @categori" do
      Categori.stub(:new) { mock_categori }
      get :new
      assigns(:categori).should be(mock_categori)
    end
  end

  describe "GET edit" do
    it "assigns the requested categori as @categori" do
      Categori.stub(:find).with("37") { mock_categori }
      get :edit, :id => "37"
      assigns(:categori).should be(mock_categori)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created categori as @categori" do
        Categori.stub(:new).with({'these' => 'params'}) { mock_categori(:save => true) }
        post :create, :categori => {'these' => 'params'}
        assigns(:categori).should be(mock_categori)
      end

      it "redirects to the created categori" do
        Categori.stub(:new) { mock_categori(:save => true) }
        post :create, :categori => {}
        response.should redirect_to(categori_url(mock_categori))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved categori as @categori" do
        Categori.stub(:new).with({'these' => 'params'}) { mock_categori(:save => false) }
        post :create, :categori => {'these' => 'params'}
        assigns(:categori).should be(mock_categori)
      end

      it "re-renders the 'new' template" do
        Categori.stub(:new) { mock_categori(:save => false) }
        post :create, :categori => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested categori" do
        Categori.stub(:find).with("37") { mock_categori }
        mock_categori.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :categori => {'these' => 'params'}
      end

      it "assigns the requested categori as @categori" do
        Categori.stub(:find) { mock_categori(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:categori).should be(mock_categori)
      end

      it "redirects to the categori" do
        Categori.stub(:find) { mock_categori(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(categori_url(mock_categori))
      end
    end

    describe "with invalid params" do
      it "assigns the categori as @categori" do
        Categori.stub(:find) { mock_categori(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:categori).should be(mock_categori)
      end

      it "re-renders the 'edit' template" do
        Categori.stub(:find) { mock_categori(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested categori" do
      Categori.stub(:find).with("37") { mock_categori }
      mock_categori.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the categoris list" do
      Categori.stub(:find) { mock_categori }
      delete :destroy, :id => "1"
      response.should redirect_to(categoris_url)
    end
  end

end
