require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PaniersController do

  def mock_panier(stubs={})
    @mock_panier ||= mock_model(Panier, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all paniers as @paniers" do
      Panier.stub(:all) { [mock_panier] }
      get :index
      assigns(:paniers).should eq([mock_panier])
    end
  end

  describe "GET show" do
    it "assigns the requested panier as @panier" do
      Panier.stub(:find).with("37") { mock_panier }
      get :show, :id => "37"
      assigns(:panier).should be(mock_panier)
    end
  end

  describe "GET new" do
    it "assigns a new panier as @panier" do
      Panier.stub(:new) { mock_panier }
      get :new
      assigns(:panier).should be(mock_panier)
    end
  end

  describe "GET edit" do
    it "assigns the requested panier as @panier" do
      Panier.stub(:find).with("37") { mock_panier }
      get :edit, :id => "37"
      assigns(:panier).should be(mock_panier)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created panier as @panier" do
        Panier.stub(:new).with({'these' => 'params'}) { mock_panier(:save => true) }
        post :create, :panier => {'these' => 'params'}
        assigns(:panier).should be(mock_panier)
      end

      it "redirects to the created panier" do
        Panier.stub(:new) { mock_panier(:save => true) }
        post :create, :panier => {}
        response.should redirect_to(panier_url(mock_panier))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved panier as @panier" do
        Panier.stub(:new).with({'these' => 'params'}) { mock_panier(:save => false) }
        post :create, :panier => {'these' => 'params'}
        assigns(:panier).should be(mock_panier)
      end

      it "re-renders the 'new' template" do
        Panier.stub(:new) { mock_panier(:save => false) }
        post :create, :panier => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested panier" do
        Panier.stub(:find).with("37") { mock_panier }
        mock_panier.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :panier => {'these' => 'params'}
      end

      it "assigns the requested panier as @panier" do
        Panier.stub(:find) { mock_panier(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:panier).should be(mock_panier)
      end

      it "redirects to the panier" do
        Panier.stub(:find) { mock_panier(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(panier_url(mock_panier))
      end
    end

    describe "with invalid params" do
      it "assigns the panier as @panier" do
        Panier.stub(:find) { mock_panier(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:panier).should be(mock_panier)
      end

      it "re-renders the 'edit' template" do
        Panier.stub(:find) { mock_panier(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested panier" do
      Panier.stub(:find).with("37") { mock_panier }
      mock_panier.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the paniers list" do
      Panier.stub(:find) { mock_panier }
      delete :destroy, :id => "1"
      response.should redirect_to(paniers_url)
    end
  end

end
